export const foodItems = [
  {
    id: 1,
    name: 'Fresh Avocado Salad',
    description: 'Mixed greens, avocado, cherry tomatoes, cucumber with lemon dressing',
    price: 1299,
    discount: 0,
    category: 'Salads',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    calories: 320,
    prepTime: 10,
    rating: 4.8,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'
  },
  {
    id: 2,
    name: 'Quinoa Power Bowl',
    description: 'Quinoa, roasted vegetables, chickpeas, tahini sauce',
    price: 1499,
    discount: 10,
    category: 'Bowls',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    calories: 450,
    prepTime: 15,
    rating: 4.7,
    image: 'https://images.pexels.com/photos/3184192/pexels-photo-3184192.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'
  },
  {
    id: 3,
    name: 'Veggie Wrap Delight',
    description: 'Grilled vegetables, hummus, spinach, and feta in a whole wheat wrap',
    price: 1099,
    discount: 5,
    category: 'Wraps',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    calories: 490,
    prepTime: 12,
    rating: 4.6,
    image: 'https://images.pexels.com/photos/574201/pexels-photo-574201.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'
  },
  {
    id: 4,
    name: 'Berry Blast Smoothie',
    description: 'Mixed berries, banana, almond milk, chia seeds',
    price: 799,
    discount: 0,
    category: 'Drinks',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    calories: 280,
    prepTime: 5,
    rating: 4.9,
    image: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'
  },
  {
    id: 5,
    name: 'Falafel Plate',
    description: 'Homemade falafel, hummus, tabbouleh, pita bread',
    price: 1399,
    discount: 15,
    category: 'Plates',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    calories: 580,
    prepTime: 18,
    rating: 4.5,
    image: 'https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'
  },
  {
    id: 6,
    name: 'Paneer Tikka Bowl',
    description: 'Marinated paneer, bell peppers, onions, served over fragrant basmati rice',
    price: 1599,
    discount: 0,
    category: 'Bowls',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    calories: 600,
    prepTime: 20,
    rating: 4.7,
    image: 'https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'
  },
  {
    id: 7,
    name: 'Greek Salad',
    description: 'Tomatoes, cucumber, olives, red onion, feta cheese, oregano, olive oil',
    price: 1199,
    discount: 0,
    category: 'Salads',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    calories: 350,
    prepTime: 10,
    rating: 4.8,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'
  },
  {
    id: 8,
    name: 'Mushroom Burger',
    description: 'Grilled portobello mushroom, lettuce, tomato, vegan cheese on a brioche bun',
    price: 1399,
    discount: 5,
    category: 'Plates',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    calories: 550,
    prepTime: 15,
    rating: 4.6,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'
  }
];
